# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('has_siblings', models.BooleanField()),
                ('environmental_exposures', models.TextField()),
                ('genetic_mutations', models.TextField()),
                ('review_status', models.CharField(choices=[('NR', 'Not Reviewed'), ('RA', 'Reviewed - Accepted'), ('RN', 'Reviewed - Not Accepted')], default='NR', max_length=2)),
            ],
        ),
    ]
